### ISSUE TITLE
Need train bash script, I got Error While training with llava1.5 bash script.

### ISSUE THREAD

**Issue by mengjiexu** [DLCV-BUAA/TinyLLaVABench#12]
I used the following train script, but get the Error:

```
Traceback (most recent call last):
  File "/home/xmj/mycipan3/smartahc_algorithm/projects/TinyLLaVABench/tinyllava/train/train.py", line 209, in <module>
    train()
  File "/home/xmj/mycipan3/smartahc_algorithm/projects/TinyLLaVABench/tinyllava/train/train.py", line 198, in train
    trainer.train()
  File "/home/xmj/anaconda3/envs/tinyllava/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/xmj/anaconda3/envs/tinyllava/lib/python3.10/site-packages/transformers/trainer.py", line 1836, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/home/xmj/anaconda3/envs/tinyllava/lib/python3.10/site-packages/accelerate/data_loader.py", line 381, in __iter__
    dataloader_iter = super().__iter__()
  File "/home/xmj/anaconda3/envs/tinyllava/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 441, in __iter__
    return self._get_iterator()
  File "/home/xmj/anaconda3/envs/tinyllava/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/xmj/anaconda3/envs/tinyllava/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1084, in __init__
    self._reset(loader, first_iter=True)
  File "/home/xmj/anaconda3/envs/tinyllava/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1117, in _reset
    self._try_put_index()
  File "/home/xmj/anaconda3/envs/tinyllava/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1351, in _try_put_index
    index = self._next_index()
  File "/home/xmj/anaconda3/envs/tinyllava/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 623, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/xmj/anaconda3/envs/tinyllava/lib/python3.10/site-packages/accelerate/data_loader.py", line 175, in _iter_with_no_split
    for idx, batch in enumerate(self.batch_sampler):
  File "/home/xmj/anaconda3/envs/tinyllava/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 254, in __iter__
    for idx in self.sampler:
  File "/home/xmj/anaconda3/envs/tinyllava/lib/python3.10/site-packages/tinyllava/train/llava_trainer.py", line 132, in __iter__
    indices = get_modality_length_grouped_indices(self.lengths, self.batch_size, self.world_size, generator=self.generator)
  File "/home/xmj/anaconda3/envs/tinyllava/lib/python3.10/site-packages/tinyllava/train/llava_trainer.py", line 65, in get_modality_length_grouped_indices
    lang_indices, lang_lengths = zip(*[(i, -l) for i, l in enumerate(lengths) if l < 0])
ValueError: not enough values to unpack (expected 2, got 0)
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
Traceback (most recent call last):
  File "/home/xmj/mycipan3/smartahc_algorithm/projects/TinyLLaVABench/tinyllava/train/train.py", line 209, in <module>
    train()
  File "/home/xmj/mycipan3/smartahc_algorithm/projects/TinyLLaVABench/tinyllava/train/train.py", line 198, in train
    trainer.train()
  File "/home/xmj/anaconda3/envs/tinyllava/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/xmj/anaconda3/envs/tinyllava/lib/python3.10/site-packages/transformers/trainer.py", line 1836, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/home/xmj/anaconda3/envs/tinyllava/lib/python3.10/site-packages/accelerate/data_loader.py", line 381, in __iter__
    dataloader_iter = super().__iter__()
  File "/home/xmj/anaconda3/envs/tinyllava/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 441, in __iter__
    return self._get_iterator()
  File "/home/xmj/anaconda3/envs/tinyllava/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/xmj/anaconda3/envs/tinyllava/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1084, in __init__
    self._reset(loader, first_iter=True)
  File "/home/xmj/anaconda3/envs/tinyllava/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1117, in _reset
    self._try_put_index()
  File "/home/xmj/anaconda3/envs/tinyllava/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1351, in _try_put_index
    index = self._next_index()
  File "/home/xmj/anaconda3/envs/tinyllava/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 623, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/xmj/anaconda3/envs/tinyllava/lib/python3.10/site-packages/accelerate/data_loader.py", line 175, in _iter_with_no_split
    for idx, batch in enumerate(self.batch_sampler):
  File "/home/xmj/anaconda3/envs/tinyllava/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 254, in __iter__
    for idx in self.sampler:
  File "/home/xmj/anaconda3/envs/tinyllava/lib/python3.10/site-packages/tinyllava/train/llava_trainer.py", line 132, in __iter__
    indices = get_modality_length_grouped_indices(self.lengths, self.batch_size, self.world_size, generator=self.generator)
  File "/home/xmj/anaconda3/envs/tinyllava/lib/python3.10/site-packages/tinyllava/train/llava_trainer.py", line 65, in get_modality_length_grouped_indices
    lang_indices, lang_lengths = zip(*[(i, -l) for i, l in enumerate(lengths) if l < 0])
ValueError: not enough values to unpack (expected 2, got 0)
[2024-03-04 17:27:49,316] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 2036910
[2024-03-04 17:27:49,637] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 2036911
[2024-03-04 17:27:49,637] [ERROR] [launch.py:321:sigkill_handler] ['/home/xmj/anaconda3/envs/tinyllava/bin/python', '-u', 'tinyllava/train/train.py', '--local_rank=1', '--lora_enable', 'True', '--bits', '8', '--lora_r', '64', '--lora_alpha', '128', '--mm_projector_lr', '1e-5', '--deepspeed', '../LLaVA/scripts/zero2.json', '--model_name_or_path', 'TinyLLaVA-3.1B', '--data_path', '/home/xmj/mycipan3/smartahc_algorithm/projects/LLaVA/playground/feeder_5label_v4/annotations_feeder_train_0220_merge.json', '--image_folder', '/home/xmj/mycipan3/smartahc_algorithm/projects/LLaVA/playground/feeder_5label_v4/gen_all_feeder_images_check', '--vision_tower', 'bczhou/TinyLLaVA-3.1B-SigLIP', '--mm_projector_type', 'mlp2x_gelu', '--mm_vision_select_layer', '-2', '--mm_use_im_start_end', 'False', '--mm_use_im_patch_token', 'False', '--image_aspect_ratio', 'pad', '--group_by_modality_length', 'True', '--bf16', 'True', '--output_dir', './checkpoints/llava-v1.5-13b-pig5classv4-3epoch-0223-bs64-lora', '--num_train_epochs', '3', '--per_device_train_batch_size', '4', '--per_device_eval_batch_size', '2', '--gradient_accumulation_steps', '8', '--evaluation_strategy', 'no', '--save_strategy', 'steps', '--save_steps', '40', '--save_total_limit', '15', '--learning_rate', '1e-4', '--weight_decay', '0.', '--warmup_ratio', '0.03', '--lr_scheduler_type', 'cosine', '--logging_steps', '1', '--tf32', 'True', '--model_max_length', '2048', '--gradient_checkpointing', 'True', '--dataloader_num_workers', '4', '--lazy_preprocess', 'True'] exits with return code = 1
```
The training script:
```sh
deepspeed tinyllava/train/train.py --lora_enable True --bits 8 --lora_r 64 --lora_alpha 128 --mm_projector_lr 1e-5 --deepspeed ../LLaVA/scripts/zero2.json --model_name_or_path TinyLLaVA-3.1B --data_path mixed_665k.json --image_folder images_check --vision_tower  bczhou/TinyLLaVA-3.1B-SigLIP --mm_projector_type mlp2x_gelu  --mm_vision_select_layer -2   --mm_use_im_start_end False --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./checkpoints/llava-v1.5-13b-3epoch-0223-bs64-lora \
    --num_train_epochs 3 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 40 \
    --save_total_limit 15 \
    --learning_rate 1e-4 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" 
```

**Comment by baichuanzhou** [comment]
If your data only contains one modality, you should set `group_by_modality_length` to False.
